### ISSUE TITLE
Erro na tela de relatórios e nas funções showRenda e showGastos

### ISSUE THREAD

**Issue by drikosv8** [zecarlos558/carteira_tech#2]
Erro na tela de relatórios e nas funções showRenda e showGastos

Consegue arrumar?

/relatorio/showGasto
/relatorio/showRenda

Amigo, curti muito sua aplicação, mas vi que ao clicar em relatorios e chamado as 2 funções recebo varios erros

Illuminate
 \ 
Database
 \ 
QueryException
PHP 8.0.26
9.52.16
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'laravel.movimentos.valor' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
SELECT
  categorias.id AS id,
  categorias.nome AS nome,
  sum(movimentos.valor) AS valorTotal,
  movimentos.tipo AS tipo
FROM
  `movimentos`
  INNER JOIN `categorias` ON `categorias`.`id` = `movimentos`.`categoria_id`
WHERE
  `movimentos`.`user_id_create` = 1
  AND `tipo` = retirada
  AND MONTH(`data`) = 05
GROUP BY
  `categorias`.`id`,
  `categorias`.`nome`,
  `movimentos`.`tipo`
ORDER BY
  `valor` DESC

Expand vendor frames
7 vendor frames
App
 \ 
Http
 \ 
Controllers
 \ 
RelatorioController
 
: 197
showGasto
48 vendor frames
C:\wamp64\www\carteira-tech\carteira_tech\app\Http\Controllers\RelatorioController
.php
 
: 197

**Comment by zecarlos558** [comment]
Ajustado agrupamento de dados dos movimentos para o relatório! Commit com correção `97ca662`
Obrigado pela observação @drikosv8 !
